/// THIS FILE SHOULD AND WILL BE ONLY ATTENDING FOR A BACKUP CAUSE FOR CARDS NOT FOUND
/// IN THE ALREADY PRESENTED DMG DATABASE, IF THE CARD IS FOUND ON THE ORG/API IT WILL
/// THEN BE STORED IN THE PRESENTED DMG DATABASE AND KEPT THERE.

import needle from 'needle'
