openapi: 3.0.0
servers:
  - url: http://localhost:3480
info:
  version: 0.1.0-beta
  title: DMG Player Microservice
  description: Create, update and delete players
tags:
  - name: Player
    description: DMG CRUD API
paths:
  /players:
    $ref: ./paths/index.yml
  /players/{id}:
    $ref: ./paths/id.yml
components:
  responses:
    400:
      $ref: ./defs/resps/400.yml
    404:
      $ref: ./defs/resps/404.yml
    500:
      $ref: ./defs/resps/500.yml
  schemas:
    Error:
      $ref: ./defs/error.yml
    PlayersView:
      $ref: ./defs/view.yml
    PlayersPost:
      $ref: ./defs/post.yml
    PlayersUpdate:
      $ref: ./defs/update.yml
    PlayersPartial:
      $ref: ./defs/partial.yml
