openapi: 3.0.0
servers:
  - url: http://localhost:3480
info:
  version: 0.1.1-beta
  title: DarkMagician CRUD API
  description: The core CRUD services for DarkMagician
tags:
  - name: Player
    description: CRUD DarkMagician's player
  - name: Decks
    description: decks linked with the player
  - name: Cards
    description: cards linked with decks
paths:
  /players:
    $ref: ./paths/players/index.yml
  /players/{id}:
    $ref: ./paths/players/:id.yml
  /decks:
    $ref: ./paths/decks/index.yml
  /decks/{id}:
    $ref: ./paths/decks/:id.yml
  /decks/{player}:
    $ref: ./paths/decks/:player.yml
  /cards:
    $ref: ./paths/cards/index.yml
  /cards/{id}:
    $ref: ./paths/cards/:id.yml
  /cards/{deck}:
    $ref: ./paths/cards/:decks.yml
  /cards/{player}:
    $ref: ./paths/cards/:player.yml
components:
  responses:
    400:
      $ref: ./defs/resps/400.yml
    404:
      $ref: ./defs/resps/404.yml
  schemas:
    Error:
      $ref: ./defs/error.yml
    DecksView:
      $ref: ./defs/decks/view.yml
    DecksPost:
      $ref: ./defs/decks/post.yml
    DecksUpdate:
      $ref: ./defs/decks/update.yml
    DecksPartial:
      $ref: ./defs/decks/partial.yml
    CardsView:
      $ref: ./defs/cards/view.yml
    CardsPost:
      $ref: ./defs/cards/post.yml
    CardsUpdate:
      $ref: ./defs/cards/update.yml
    CardsPartial:
      $ref: ./defs/cards/partial.yml
    PlayerView:
      $ref: ./defs/players/view.yml
    PlayerPost:
      $ref: ./defs/players/post.yml
    PlayerUpdate:
      $ref: ./defs/players/update.yml
    PlayerPartial:
      $ref: ./defs/players/partial.yml
