#!/bin/bash

if [ $PWD != "/home/$USER/DarkMagician" ]; then
	echo "please use `git` commands in the project's root."

	exit 1
fi

echo "Installing packages..."

npm ci
if [ $? -eq 0 ]; then
	npm run build
	if [ $? -eq 0 ]; then
		npm run test
		if [ $? -eq 0 ]; then
			exit 0
		else
			exit 1
		fi
	else
		exit 1
	fi
else
	exit 1
fi