#!/bin/bash

## NODE

PROJECT_DIR="/home/$USER/DarkMagician"

if [ $PWD != PROJECT_DIR ]; then
	echo "please use `git` commands in the project's root."

	exit 1
fi

npm ci
	&& npm run build
	&& npm run test

## RUST

for service in "$PROJECT_DIR"/*
do
	cargo test --manifest-path="$service"
	cargo build --manifest-path="$service"
done
