#!/bin/bash

ROOT = "/home/$USER/DarkMagician"

if [ $PWD != ROOT ]; then
	echo "please use `git` commands in the project's root."

	exit 1
fi

## NODE

npm run lint

## RUST

for service in "$ROOT"/*
do
	cargo clippy --manifest-path="$ROOT" -- -D warningsd 
done