#!/bin/bash

PROJECT_DIR = "/home/$USER/DarkMagician"

if [ $PWD != PROJECT_DIR ]; then
	echo "please use `git` commands in the project's root."

	exit 1
fi

## NODE

npm run lint

## RUST

for service in "$PROJECT_DIR/services"/*
do
	cargo clippy --manifest-path="$service" -- -D warnings 
done