openapi: 3.0.0
servers:
  - url: 'http://localhost:3480'
info:
  version: 0.1.0-beta
  title: DMG Player Microservice
  description: 'Create, update and delete players'
tags:
  - name: Player
    description: DMG CRUD API
paths:
  /players:
    get:
      summary: get all player instances
      tags:
        - Player
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayersView'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    post:
      summary: create a player instance
      tags:
        - Player
      requestBody:
        description: player instance to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayersPost'
      responses:
        '204':
          description: No content
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  '/players/{id}':
    get:
      summary: get a player instance with their ID
      tags:
        - Player
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: player/user's ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersView'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    patch:
      summary: update a player instance with their ID
      tags:
        - Player
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: player/user's ID
      responses:
        '204':
          description: no content
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: delete a player isntance with their ID
      tags:
        - Player
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: player/user's ID
      responses:
        '204':
          description: no content
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
components:
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          example: 404
          description: Error status code
        message:
          type: string
          example: not found
          description: Error message
    PlayersView:
      allOf:
        - $ref: '#/components/schemas/PlayersPartial'
        - type: object
          required:
            - id
            - bal
    PlayersPost:
      allOf:
        - $ref: '#/components/schemas/PlayersPartial'
        - type: object
          required:
            - id
    PlayersUpdate:
      allOf:
        - $ref: '#/components/schemas/PlayersPartial'
        - type: object
          required:
            - bal
    PlayersPartial:
      type: object
      properties:
        id:
          type: string
          example: 137217868436733950
          description: Player's Discord ID
        bal:
          type: number
          example: 5625
          description: Player's Balance
