#!/bin/bash
set -e

USER="magician"
READONLY=${READONLY_ROLE}

if [ -e /run/secrets/PG_DMG_PASSWORD ]; then
	PASSW="$(< /run/secrets/PG_DMG_PASSWORD)"
else
	PASSW=${PG_DMG_PASSWORD}
fi

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE $READONLY;

  CREATE USER $USER WITH ENCRYPTED PASSWORD '$PASSW';
  GRANT $READONLY TO $USER;
EOSQL
