name: '[Node Port] Dark Magician (Github Actions)'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building dmg
        run: yarn && yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing dark magician
        run: yarn && yarn test
      - uses: paambaati/codeclimate-action@v2.7.1
        name: publish code coverage
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TC_TOKEN}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/players/coverage/lcov.info:lcov
            ${{github.workspace}}/packages/commons/coverage/lcov.info:lcov
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: linting dark magician
        run: yarn && yarn lint -- -- --quiet
