name: '[Node Port] Dark Magician (Github Actions)'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building dark magician
        run: npm i && npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing dark magician
        run: npm i && npm run test
      - uses: paambaati/codeclimate-action@v2.7.1
        name: publish code coverage
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TC_TOKEN}}
        with: |
          :/packages/players/coverage/lcov.info
          :/packages/commons/coverage/lcov.info
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: linting dark magician
        run: npm i && npm run lint -- -- --quiet
