name: '[Rust Port] Dark Magician (Github Actions)'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: building [dmg-services] cards
        run: cargo build --manifest-path="../../services/cards/Cargo.toml"
      - name: building [dmg-services] imgm
        run: cargo build --manifest-path="../../services/imgm/Cargo.toml"
