name: Magician's Standard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stable:
    runs-on: ubuntu-latest
		matrix:
        node-version: [12.x, 14.x, 16.x]
        redis-version: [4, 5, 6]

    steps:
      - uses: actions/checkout@v2
			- uses: supercharge/redis-github-action@1.2.0
				with:
					redis-version: ${{ matrix.redis-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: installing
        run: npm ci
      - name: building
        run: npm run build
      - name: testing
        run: npm run test
