name: magician standard

on:
	push:
		branches: [ main ]

jobs:
	stable:
		runs-on: ubuntu-latest

		strategy:
			matrix:
				node-version: [ 10.x, 12.x, 14.x, 15.x ]

		steps:
			- uses: actions/checkout@v2
			- name: 'using node'
				uses: actions/setup-node@v2
				with: ${{ matrix.node-version }}
			- name: install
				run: npm ci
			- name: build
				run: npm run build
			- name: test
				run: npm run test
