name: Magician's Standard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: 6.x
          auto-start: "true" 
          redis-port: 6770
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: installing
        run: npm ci
      - name: building
        run: npm run build
      - name: testing
        run: npm run test
