name: DarkMagician StandardCI

on:
	push:
		branches: [ main ]

jobs:
	standard:

		runs-on: ubuntu-latest

		strategy:
			matrix:
				node-version: [ 10.x, 12.x, 14.x, 15.x ]

		steps:
			- uses: actions/checkout@v2
			- name: 'using node'
				uses: actions/setup-node@v2
				with: ${{ matrix.node-version }}
			- name: Install deps
				run: npm ci
			- name: Build pacakges
				run: npm run build
			- name: Test pacakges
				run: npm run test
